### PR TITLE
fix(cli): use namespace from user context when --namespace is not set

### LINKED ISSUE #1579: Not able to do packet capture, fails with "Error: the server does not allow this method on the requested resource"
**Describe the bug**
I am trying to do a packet capture. It fails with the following error:

```
ts=2025-05-05T22:54:11.485+0530 level=error caller=capture/create.go:133 msg="Failed to create job" error="the server does not allow this method on the requested resource"
Error: the server does not allow this method on the requested resource
```

**To Reproduce**
```
$ kubectl retina capture create --pod-selectors="app=foobar"
ts=2025-05-05T22:54:09.013+0530 level=info caller=capture/create.go:259 msg="The capture duration is set to 1m0s"
ts=2025-05-05T22:54:09.013+0530 level=info caller=capture/create.go:266 msg="Overriding default node selectors value and setting it to nil. Using namespace and pod selectors. To use node selector, please remove namespace and pod selectors."
ts=2025-05-05T22:54:09.013+0530 level=info caller=capture/create.go:313 msg="The capture file max size is set to 100MB"
ts=2025-05-05T22:54:09.013+0530 level=info caller=utils/capture_image.go:57 msg="Using capture workload image ghcr.io/microsoft/retina/retina-agent:v0.0.32 with version determined by CLI version"
ts=2025-05-05T22:54:09.015+0530 level=info caller=capture/crd_to_job.go:202 msg="HostPath is not empty" HostPath=/mnt/retina/captures
ts=2025-05-05T22:54:11.235+0530 level=info caller=capture/crd_to_job.go:902 msg="The Parsed tcpdump filter is \"\""
#########################
Expected Capture Files
#########################
retina-capture-i-1234-20250505172411UTC.tar.gz
retina-capture-i-4321-20250505172411UTC.tar.gz

Note: The file(s) may not be created if the capture job(s) fail prematurely.
#########################
ts=2025-05-05T22:54:11.485+0530 level=error caller=capture/create.go:133 msg="Failed to create job" error="the server does not allow this method on the requested resource"
Error: the server does not allow this method on the requested resource
Usage:
  kubectl-retina capture create [flags]

```

**Expected behavior**
Packet capture should happen.

**Platform (please complete the following information):**

- OS: [e.g. AzureLinux] Ubuntu 22.04
- Kubernetes Version: [e.g. 1.22] 1.29
- Host: [e.g. AKS, KIND, self-host, etc] self hosted with `kOps`
- Retina Version: v0.0.32

### PR DESCRIPTION
**Pull request by alexcastilio**
# Description

Currently when trying to create a capture and `--namespace` is not set, retina-kubectl does not work as expected which would be to create a capture in the namespace set in user's kubectl context.

This PR fixes this issue by setting namespace based on user's kubectl context.

## Related Issue

Fixes #1579

## Checklist

- [ ] I have read the [contributing documentation](https://retina.sh/docs/Contributing/overview).
- [ ] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [ ] I have correctly attributed the author(s) of the code.
- [ ] I have tested the changes locally.
- [ ] I have followed the project's style guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Test:
```bash
./artifacts/kubectl-retina capture create --node-names "aks-nodepool1-17156767-vmss000000" --duration 5s --name test
ts=2025-06-18T09:20:02.268+0100 level=info caller=capture/create.go:274 msg="Capture timestamp: 2025-06-18 08:20:02 +0000 UTC"
ts=2025-06-18T09:20:02.269+0100 level=info caller=capture/create.go:277 msg="The capture duration is set to 5s"
ts=2025-06-18T09:20:02.269+0100 level=info caller=capture/create.go:331 msg="The capture file max size is set to 100MB"
ts=2025-06-18T09:20:02.269+0100 level=info caller=utils/capture_image.go:57 msg="Using capture workload image ghcr.io/microsoft/retina/retina-agent:v0.0.34-10-g8e41f1b with version determined by CLI version"
ts=2025-06-18T09:20:02.276+0100 level=info caller=capture/crd_to_job.go:203 msg="HostPath is not empty" HostPath=/mnt/retina/captures
ts=2025-06-18T09:20:03.218+0100 level=info caller=capture/crd_to_job.go:902 msg="The Parsed tcpdump filter is \"\""
#########################
Expected Capture Files
#########################
test-aks-nodepool1-17156767-vmss000000-20250618082002UTC.tar.gz

Note: The file(s) may not be created if the capture job(s) fail prematurely.
#########################
ts=2025-06-18T09:20:03.397+0100 level=info caller=capture/create.go:411 msg="Packet capture job is created" namespace=default capture job=test-n55p4
ts=2025-06-18T09:20:03.397+0100 level=info caller=capture/create.go:148 msg="Please manually delete all capture jobs"
NAMESPACE   CAPTURE NAME   JOB          COMPLETIONS   AGE
default     test           test-n55p4   0/1           0s

./artifacts/kubectl-retina capture delete --name test
ts=2025-06-18T09:20:54.962+0100 level=info caller=capture/delete.go:94 msg="Retina Capture \"test\" delete"
```

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

File: cli/cmd/capture/download.go [hunk 1]
```diff
@@ -404,9 +404,6 @@ func downloadFromBlob() error {
 	return nil
 }
 
-func init() {
-	capture.AddCommand(downloadCapture)
-	downloadCapture.Flags().StringVar(&blobURL, "blob-url", "", "Blob URL from which to download")
```
Comment (kamilprz) [inline cli/cmd/capture/download.go]: Removing the flags from here now means that `k retina capture download -h` does not show them.

e.g.

```
> k retina capture download -h
Download Retina Captures

Usage:
  kubectl-retina capture download [flags]

Examples:
  # List Retina capture jobs
  kubectl retina capture list

  # Download the capture file(s) created using the capture name
  kubectl retina capture download --name <capture-name>

  # Download the capture file(s) created using the capture name and define output location
  kubectl retina capture download --name <capture-name> -o <output-location>

  # Download capture file(s) from Blob Storage via Blob URL (Blob URL requires Read/List permissions)
  kubectl retina capture download --blob-url "<blob-url>"

Flags:
  -h, --help   help for download

Global Flags:
      --as string                      Username to impersonate for the operation. User could be a regular user or a service account in a namespace.
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --as-uid string                  UID to impersonate for the operation.
      --cache-dir string               Default cache directory (default "/home/kamilp/.kube/cache")
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
      --disable-compression            If true, opt-out of response compression for all requests to the server
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests.
      --name string                    The name of the Retina Capture (default "retina-capture")
  -n, --namespace string               If present, the namespace scope for this CLI request
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                  The address and port of the Kubernetes API server
      --tls-server-name string         Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
```

File: cli/cmd/capture/create_test.go [hunk 2]
```diff
@@ -0,0 +1,313 @@
...
+	inputNamespace    string
+	wantNamespace     string
+	inputPodSelector  string
+	inputNsSelector   string
+	inputNodeSelector string
+	wantNodes         []string
+	wantErr           bool
+}
+
+func randomString(length int) string {
```
Comment (kamilprz) [inline cli/cmd/capture/create_test.go]: why not `rand.String(n)` ?

File: cli/cmd/capture/create_test.go [hunk 3]
```diff
@@ -0,0 +1,313 @@
...
+				job.Name = job.GenerateName + randomString(5)
+			}
+			return false, job, nil
+		})
+
+		return kubeClient
+	}
+
+	// Setup test cases
+	testCases := []testcase{
```
Comment (kamilprz) [inline cli/cmd/capture/create_test.go]: Could we get a test case with just one of PodSelector / NamespaceSelectors ? They should be paired together, so worth verifying behaviour when isolated.

File: cli/cmd/capture/create_test.go [hunk 4]
```diff
@@ -0,0 +1,313 @@
...
+			wantNamespace:    "default",
+			inputPodSelector: "service=A",
+			inputNsSelector:  "name=workload",
+			wantNodes:        []string{"A1", "A2"},
+			wantErr:          false,
+		},
+		{
+			name:             "create --namespace=workload --podSelector=service=A --namespace-selectors=name=workload",
+			inputName:        "",
+			wantName:         "retina-capture", // Default name for capture job
```
Comment (kamilprz) [inline cli/cmd/capture/create_test.go]: Maybe capture this in a const rather than multiple comments?

File: cli/cmd/capture/download.go (hunk 1 above)
Comment (alexcastilio) [reply cli/cmd/capture/download.go]: Thanks for spotting it. Re-added flags.

**Review by matmerr — CHANGES_REQUESTED** [review]
let's move the fix for this pr into a specific isolated change, and the opts/capture command into a separate refactor pr

there's quite a bit happening here other than use namespace from a flag

**Review by ibezrukavyi — APPROVED** [review]

**Comment by alexcastilio** [comment]
> let's move the fix for this pr into a specific isolated change, and the opts/capture command into a separate refactor pr
> 
> there's quite a bit happening here other than use namespace from a flag

@matmerr New PR: https://github.com/microsoft/retina/pull/1693
