### PR TITLE
fix: add guard clause for MetricsInterval

### LINKED ISSUE #2029: [Bug] Retina Agent panics on startup when MetricsInterval is not provided
**Describe the bug**
The retina-agent panics and enters a CrashLoopBackOff during initialization if the MetricsInterval is not explicitly set in the configuration. The pluginmanager returns a hard error (ErrZeroInterval) when the value is 0, which triggers a panic in the controller manager.
**To Reproduce**

1. Clone the Retina repository on a Mac (ARM64).
2. Create a local cluster using kind.
3. Install Retina using the "Standard" Helm chart: helm install retina ./deploy/standard/manifests/controller/helm/retina --namespace kube-system.
4. Observe the retina-agent pods crashing.
5. Check logs: kubectl logs -n kube-system <retina-agent-pod>.

**Expected behavior**
The agent should ideally start with a sensible default MetricsInterval (e.g., 10s) and log a warning if the value is missing or zero, rather than panicking and crashing the pod.

**Screenshots**
Image

**Platform (please complete the following information):**

OS: macOS (running Linux nodes via Docker/Kind)
Kubernetes Version: v1.35.0 (based on your logs)
Host: KIND
Retina Version: v0.0.2

**Additional context**
The panic occurs at pkg/managers/pluginmanager/pluginmanager.go:119. The logs indicate: panic: Error running controller manager ... error="pluginmanager requires a positive MetricsInterval in its config". It appears the "Standard" Helm chart does not provide a default value for this field that the Go code accepts. I am interested in contributing a fix that adds a default value in the code to improve the local development experience.

### PR DESCRIPTION
**Pull request by uuditmisra**
Prevent panic: runtime error: invalid duration when MetricsInterval is missing or set to 0. Added a default fallback to 10s and a warning log to inform the user of the configuration issue.

Closes #2029

# Description

Please provide a brief description of the changes made in this pull request.

## Related Issue

If this pull request is related to any issue, please mention it here. Additionally, make sure that the issue is assigned to you before submitting this pull request.

## Checklist

- [x] I have read the [contributing documentation](https://retina.sh/docs/Contributing/overview).
- [x] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [x] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Please add any relevant screenshots or GIFs to showcase the changes made.

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

**Comment by uuditmisra** [comment]
@microsoft-github-policy-service agree

File: pkg/plugin/dropreason/dropreason_linux.go
Comment (nddq) [inline pkg/plugin/dropreason/dropreason_linux.go:1]: this fix should be applied at the `pluginmanager` level, in the `Start` function, fixing it here only helps the dropreason plugin, other plugins that use `MetricsInterval` would still error out

File: pkg/plugin/dropreason/dropreason_linux_test.go [hunk 1]
```diff
@@ -387,6 +387,57 @@ func TestDropReasonReadData_WithPerfArrayLostSamples(t *testing.T) {
 	time.Sleep(2 * time.Second)
 }
 
+func TestReadBasicMetricsData_InvalidIntervalDefaultsTo10s(t *testing.T) {
```
Comment (nddq) [inline pkg/plugin/dropreason/dropreason_linux_test.go]: I think we can simplify this test further. We only need to assert that the ticker is created without panic, something like this would suffice
```go
dr := &dropReason{
        cfg: &kcfg.Config{
                MetricsInterval: tt.interval,
                EnablePodLevel:  false,
        },
        l:              log.Logger().Named(name),
        metricsMapData: mockedMap,
}

ctx, cancel := context.WithCancel(context.Background())
cancel()

require.NotPanics(t, func() {
        dr.readBasicMetricsData(ctx)
})
```

File: pkg/plugin/dropreason/dropreason_linux.go
Comment (uuditmisra) [reply pkg/plugin/dropreason/dropreason_linux.go:1]: Updated as per your comment
