### PR TITLE
fix: fix zap.Any logging issues causing unsupported value type errors

### LINKED ISSUE #1680: zap.any always logs  "unsupported value type", which is not informative.
**Describe the bug**

Im trying to use  the metric adv_node_apiserver_no_response to detect apiserver problems in my clusters.

```
| `adv_node_apiserver_no_response`           | ***Advanced***: number of packets that did not get a response from API server |          
```

I created a "vanilla" EKS cluster with K8s 1.30 and then look at the value reported by  the retina metric. 
To my surprise I saw it was increasing over and over. The cluster, besides that metric, does not seem to have issues or apiserver problems so I enabled debug loglevel to see what the actual problem was.

But from here https://github.com/microsoft/retina/blame/b76bbcdb0ede6665d75755eaf0d8fd0ae07edfd0/pkg/module/metrics/latency.go#L126-L130 logged message from zap.Any is always 

"unsupported value type"

which is not informative or helpful 

Example of the messages I get
```
ts=2025-06-12T14:49:33.339Z level=debug caller=metrics/latency.go:126 msg="Evicted item" item= itemError="unsupported value type"
ts=2025-06-12T14:43:38.295Z level=debug caller=metrics/latency.go:129 msg="Incremented no response metric" metric= metricError="unsupported value type"
...
....
...

``` 

**To Reproduce**

1. Change loglevel to Debug

**Expected behavior**
1 I expect the metric or item error to be more descriptive.  

**Platform (please complete the following information):**

- Kubernetes Version: 1.30
- Host:  EKS
- Retina Version:  v0.0.34

### PR DESCRIPTION
**Pull request by agrawaliti**
## Problem

The `zap.Any` logger was being used with complex objects in the latency metrics module, resulting in uninformative "unsupported value type" error messages that made debugging difficult:

```
ts=2025-06-12T14:49:33.339Z level=debug caller=metrics/latency.go:126 msg="Evicted item" item= itemError="unsupported value type"
ts=2025-06-12T14:43:38.295Z level=debug caller=metrics/latency.go:129 msg="Incremented no response metric" metric= metricError="unsupported value type"
```

## Solution

Replaced `zap.Any` calls with appropriate structured logging using specific zap field types:

### Before (problematic):
```go
lm.l.Debug("Evicted item", zap.Any("item", item))
lm.l.Debug("Incremented no response metric", zap.Any("metric", lm.noResponseMetric))
lm.l.Debug("Add apiserver ips", zap.Any("ips", apiServerIPs))
```

### After (fixed):
```go
k := item.Key()
v := item.Value()
lm.l.Debug("Evicted item", 
    zap.String("srcIP", k.srcIP),
    zap.String("dstIP", k.dstIP),
    zap.Uint32("srcPort", k.srcP),
    zap.Uint32("dstPort", k.dstP),
    zap.Uint64("id", k.id),
    zap.Int32("timestamp", v.t))

lm.l.Debug("Incremented no response metric", zap.String("metric", "adv_node_apiserver_no_response"))

ipStrings := make([]string, len(apiServerIPs))
for i, ip := range apiServerIPs {
    ipStrings[i] = ip.String()
}
lm.l.Debug("Add apiserver ips", zap.Strings("ips", ipStrings))
```

### Logs before and after: 
```` 
ts=2025-06-12T14:49:33.339Z level=debug caller=metrics/latency.go:126 msg="Evicted item" item= itemError="unsupported value type"
ts=2025-06-12T14:43:38.295Z level=debug caller=metrics/latency.go:129 msg="Incremented no response metric" metric= metricError="unsupported value type"
````
```
ts=2025-07-23T16:20:50.047Z level=debug caller=metrics/latency.go:128 msg="Evicted item" srcIP=10.224.0.4 dstIP=20.13.226.96 srcPort=56272 dstPort=443 id=614403966 timestamp=543825424
ts=2025-07-23T16:20:50.047Z level=debug caller=metrics/latency.go:137 msg="Incremented no response metric" metric=adv_node_apiserver_no_response
```

## Benefits

- **Informative logging**: Debug messages now show actual values instead of "unsupported value type"
- **Better debugging**: Network connection details (IPs, ports, timestamps) are clearly visible
- **Structured data**: Proper field names make log parsing and analysis easier
- **No breaking changes**: Only affects debug log output format

## Testing

- All existing tests pass (23/23)
- No "unsupported value type" errors from latency.go in test output
- Verified structured logging produces readable output with meaningful field names

Fixes #1680.

---

💡 You can make Copilot smarter by setting up custom instructions, customizing its development environment and configuring Model Context Protocol (MCP) servers. Learn more [Copilot coding agent tips](https://gh.io/copilot-coding-agent-tips) in the docs.

### CODE REVIEW

**Comment by agrawaliti** [comment]
Signed PR of: https://github.com/microsoft/retina/pull/1704

File: pkg/module/metrics/latency.go [hunk 1]
```diff
@@ -123,10 +123,18 @@ func (lm *LatencyMetrics) Init(metricName string) {
...
+				zap.String("srcIP", k.srcIP),
+				zap.String("dstIP", k.dstIP),
+				zap.Uint32("srcPort", k.srcP),
+				zap.Uint32("dstPort", k.dstP),
+				zap.Uint64("id", k.id),
+				zap.Int32("timestamp", v.t))
 			if lm.noResponseMetric != nil {
 				lm.noResponseMetric.WithLabelValues("no_response").Inc()
-				lm.l.Debug("Incremented no response metric", zap.Any("metric", lm.noResponseMetric))
+				lm.l.Debug("Incremented no response metric", zap.String("metric", "adv_node_apiserver_no_response"))
```
Comment (ritwikranjan) [inline pkg/module/metrics/latency.go]: Is the hardcoding of `"adv_node_apiserver_no_response"` intended?

**Review by ritwikranjan — COMMENTED** [review]
lgtm other than the hardcoded metric name.

**Comment by agrawaliti** [comment]
Verified logs with the final changes

```
ts=2025-07-30T12:50:25.048Z level=debug caller=metrics/latency.go:128 msg="Evicted item" srcIP=10.224.0.4 dstIP=20.116.148.139 srcPort=56124 dstPort=443 id=559864698 timestamp=425380656
ts=2025-07-30T12:50:25.048Z level=debug caller=metrics/latency.go:137 msg="Incremented no response metric" metric=adv_node_apiserver_no_response
ts=2025-07-30T12:50:25.082Z level=debug caller=packetparser/packetparser_linux.go:564 msg="Received record" cpu=3 lost_samples=0 bytes_remaining=136 worker_id=0
--
```
