### PR TITLE
fix(bug): ignore headless svc to prevent error messages

### LINKED ISSUE #547: Errors when using ExternalName or Headless services
**Describe the bug**
Retina agents log a lot of error messages when having headless service in the cluster or of type ExternalName.

``` log
updateSvc: error getting primary IP for service
no primary IP found for service myService
```

**To Reproduce**

1. Deploy externalname or headless service to the cluster
2. Observe agent logs

**Expected behavior**
Retina should just ignore those services (or use endpoint ips of headless service?)

**Platform (please complete the following information):**

- OS: AzureLinux
- Kubernetes Version: 1.19
- Host: AKS
- Retina Version: 0.0.12

**Additional Information:**
I guess the relevant code is this, where it tries to save ClusterIP, even though not all services is k8s have a ClusterIP

https://github.com/microsoft/retina/blob/b71ec003ad1bb313524ea30e6fc8368c4ce249ab/pkg/controllers/daemon/service/controller.go#L78

https://github.com/microsoft/retina/blob/b71ec003ad1bb313524ea30e6fc8368c4ce249ab/pkg/common/service.go#L46

### PR DESCRIPTION
**Pull request by SRodi**
# Description

* update service controller to ignore headless svc and re-trigger reconcile when encountering one
* create test to validate UpdateRetinaSvc still throws an error if a retina svc has no IPv4 (this is to make sure existing validation post retinaSvc creation is not broken)

## Related Issue

If this pull request is related to any issue, please mention it here. Additionally, make sure that the issue is assigned to you before submitting this pull request.

fix #547 

## Checklist

- [x] I have read the [contributing documentation](https://retina.sh/docs/contributing).
- [x] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [x] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Please add any relevant screenshots or GIFs to showcase the changes made.

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

File: pkg/controllers/daemon/service/controller.go [hunk 1]
```diff
@@ -74,9 +74,12 @@ func (r *ServiceReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 		}
 		return ctrl.Result{}, nil
 	}
+	// ignore headless services
+	if service.Spec.ClusterIP == "None" {
+		return ctrl.Result{}, nil
+	}
 	ips := retinaCommon.IPAddresses{}
 	ips.IPv4 = net.ParseIP(service.Spec.ClusterIP)
-	net.ParseIP(service.Spec.ClusterIP)
```
Comment (ibezrukavyi) [inline pkg/controllers/daemon/service/controller.go:79]: any idea why this line was here?

Comment (SRodi) [reply pkg/controllers/daemon/service/controller.go:79]: No but I removed it as it is not necessary - according to the doc `net.ParseIP` returns a `net.IP` which was not assigned to anything in the line I removed.

```go
func net.ParseIP(s string) net.IP
ParseIP parses s as an IP address, returning the result. The string s can be in IPv4 dotted decimal ("192.0.2.1"), IPv6 ("2001:db8::68"), or IPv4-mapped IPv6 ("::ffff:192.0.2.1") form. If s is not a valid textual representation of an IP address, ParseIP returns nil.
```

File: pkg/controllers/daemon/service/controller.go [hunk 2]
```diff
@@ -74,9 +74,12 @@ func (r *ServiceReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 		}
 		return ctrl.Result{}, nil
 	}
+	// ignore headless services
+	if service.Spec.ClusterIP == "None" {
+		return ctrl.Result{}, nil
+	}
```
Comment (rbtr) [inline pkg/controllers/daemon/service/controller.go:80]: do we want to always, unconditionally, ignore headless services? 
if so, maybe we could filter the events out before they even hit the reconciler.
I haven't evaluated how possible it is for this Object type and field, but [here's how we have done some event filters](https://github.com/Azure/azure-container-networking/blob/251959ac63e361898baa5089f29a548a120fc044/cns/kubecontroller/nodenetworkconfig/reconciler.go#L164-L186) or [here's how we have filtered even earlier in the ctrlmanager cache layer](https://github.com/Azure/azure-container-networking/blob/251959ac63e361898baa5089f29a548a120fc044/cns/service/main.go#L1328-L1343).

Comment (SRodi) [reply pkg/controllers/daemon/service/controller.go]: according to the #547 the expected behavior is to ignore headless services. I have opted for the event filters implementation in [pkg/controllers/daemon/service/controller.go](https://github.com/microsoft/retina/pull/763/files#diff-81cc88e0d83f3f5284a95530b0781f2dbb805aaf11c7f5f0f55e57b30978cba3)

**Review by ibezrukavyi — APPROVED** [review]

**Review by rbtr — APPROVED** [review]
