### PR TITLE
fix: remove inactive connections' IP addresses from tcp_connection_remote metric

### LINKED ISSUE #382: IP addresses from closed connections still showing up in `TCP Active Connections by Remote Addr`
- A clean up function is needed to remove IP addresses that we are no longer seeing in `netstat` from `networkobservability_tcp_connection_remote` metric

### PR DESCRIPTION
**Pull request by nddq**
# Description

closes #382 

image
image

## Related Issue

If this pull request is related to any issue, please mention it here. Additionally, make sure that the issue is assigned to you before submitting this pull request.

## Checklist

- [ ] I have read the [contributing documentation](https://retina.sh/docs/contributing).
- [ ] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [ ] I have correctly attributed the author(s) of the code.
- [ ] I have tested the changes locally.
- [ ] I have followed the project's style guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Please add any relevant screenshots or GIFs to showcase the changes made.

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

File: pkg/plugin/linuxutil/netstat_stats_linux.go [hunk 1]
```diff
@@ -251,6 +253,19 @@ func (nr *NetstatReader) updateMetrics() {
 	metrics.UDPConnectionStats.WithLabelValues(utils.Active).Set(float64(nr.connStats.UdpSockets.totalActiveSockets))
 }
 
+func getAddrAndPort(remoteAddr string) (addr, port string) {
```
Comment (rbtr) [inline pkg/plugin/linuxutil/netstat_stats_linux.go:256]: https://pkg.go.dev/net/netip#ParseAddrPort instead, maybe?

**Review by spencermckee — APPROVED** [review]
