### PR TITLE
fix(conntrack): delete keys in eBPF instead of user space

### LINKED ISSUE #807: [conntrack] improving GC by removing an entry directly in bpf
Currently, for closing TCP connections, we mark the corresponding entry in conntrack and rely on the userspace process to delete it later. This step is unnecessary, as we can immediately handle the deletion in the BPF layer.

### PR DESCRIPTION
**Pull request by SRodi**
# Description

Delete TCP connections in `retina_conntrack` map directly in the eBPF layer instead of relying on the userspace process to delete it later when the connection is closing and has exceeded its lifetime.

* remove `is_closing` flag from `retina_conntrack` map, update userspace and bpf program accordingly
* delete connection from `retina_conntrack` map if connection is timed out or when FIN or RST flags are set
* invoke `bpf_map_delete_elem` in`_ct_should_report_packet` and remove update `seen_flags` and `last_report`

## Related Issue

fix #807 

## Checklist

- [x] I have read the [contributing documentation](https://retina.sh/docs/contributing).
- [x] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [x] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests, if applicable.

## Screenshots (if applicable) or Testing Completed

Please add any relevant screenshots or GIFs to showcase the changes made.

## Additional Notes

Add any additional notes or context about the pull request here.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

File: pkg/plugin/conntrack/_cprog/conntrack.c [hunk 1]
```diff
@@ -323,9 +328,9 @@ static __always_inline __attribute__((unused)) bool ct_process_packet(struct pac
...
         p->is_reply = true;
         p->traffic_direction = entry->traffic_direction;
-        return _ct_should_report_packet(entry, p->flags, CT_PACKET_DIR_RX, key.proto);
+        return _ct_should_report_packet(entry, p->flags, CT_PACKET_DIR_RX, &key);
     }
 
     // If the connection is still not found, the connection is new.
     return _ct_handle_new_connection(p, key, reverse_key, observation_point);
-}
+}
```
Comment (timraymond) [inline pkg/plugin/conntrack/_cprog/conntrack.c:336]: Newline EOF

**Review by timraymond — COMMENTED** [review]
This looks pretty reasonable to me, but I don't feel confident approving it. @nddq should take a look.

File: pkg/plugin/conntrack/_cprog/conntrack.c [hunk 2]
```diff
@@ -243,8 +246,10 @@ static __always_inline bool _ct_should_report_packet(struct ct_entry *entry, __u
 
     // Check if the connection timed out or if it is a TCP connection and FIN or RST flags are set.
     if (now >= eviction_time || (protocol == IPPROTO_TCP && flags & (TCP_FIN | TCP_RST))) {
-        // The connection is closing or closed. Mark the connection as closing. Update the flags seen and last report time.
-        WRITE_ONCE(entry->is_closing, true);
+        // The connection is closing or closed. Delete the connection from the map
+        bpf_map_delete_elem(&retina_conntrack, key);
+
+        // Update the flags seen and last report time.
```
Comment (nddq) [inline pkg/plugin/conntrack/_cprog/conntrack.c:252]: we don't have to update these if we deleted the entry, we could return true immediately

**Review by nddq — CHANGES_REQUESTED** [review]

**Review by nddq — APPROVED** [review]
