### PR TITLE
fix: capture commands should respect --namespace

### LINKED ISSUE #477: Flag not working: --namespace Flag doesn't work with Retina Capture Create
**Describe the bug**
Thanks in advance for taking a look at this. When providing the `--namespace` flag to `retina capture create`, it still uses the `default` namespace instead of the provided namespace.

**To Reproduce**

1. Install retina in any metric mode with capture support
2. Download the v0.0.12 retina binary
3. Start some capture passing the --namespace flag in the command

**Sample command:**
`kubectl-retina-darwin-arm64 capture --namespace monitoring create --duration 15s --name capture-test --s3-bucket "xxx" --s3-region "xxx" --s3-access-key-id "xxx" --s3-secret-access-key "xxx" --node-selectors "kubernetes.io/os=linux"`

**Screenshots**
Screenshot 2024-06-17 at 15 05 31
Screenshot 2024-06-17 at 15 06 22
Screenshot 2024-06-17 at 15 06 40

**Expected behavior**

- Retina cli create the k8s jobs and capture records in the designated namespace.

**Platform (please complete the following information):**

- OS: macOS 13.3.1 (22E261) + Darwin 22.4.0
- Kubernetes Version: 1.29
- Host: AWS EKS
- Retina Version: v0.0.12

**Additional context**

### PR DESCRIPTION
**Pull request by rbtr**
# Description

Fix `capture` subcommands to respect the cli-runtime `--namespace` CLI flag.

## Related Issue

Closes #477

## Checklist

- [x] I have read the [contributing documentation](https://retina.sh/docs/contributing).
- [x] I signed and signed-off the commits (`git commit -S -s ...`). See [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on signing commits.
- [x] I have correctly attributed the author(s) of the code.
- [x] I have tested the changes locally.
- [x] I have followed the project's style guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests, if applicable.

---

Please refer to the [CONTRIBUTING.md](../CONTRIBUTING.md) file for more information on how to contribute to this project.

### CODE REVIEW

File: cli/cmd/capture/create.go [hunk 1]
```diff
@@ -124,10 +120,10 @@ var createCapture = &cobra.Command{
 		if nowait {
 			retinacmd.Logger.Info("Please manually delete all capture jobs")
 			if capture.Spec.OutputConfiguration.BlobUpload != nil {
-				retinacmd.Logger.Info("Please manually delete capture secret", zap.String("namespace", namespace), zap.String("secret name", *capture.Spec.OutputConfiguration.BlobUpload))
+				retinacmd.Logger.Info("Please manually delete capture secret", zap.String("namespace", *opts.Namespace), zap.String("secret name", *capture.Spec.OutputConfiguration.BlobUpload))
```
Comment (timraymond) [inline cli/cmd/capture/create.go:123]: Might be nice to DRY these zap params. Maybe make a child logger for use within this func?

File: cli/cmd/capture/capture.go [hunk 2]
```diff
@@ -9,7 +9,10 @@ import (
 	"k8s.io/cli-runtime/pkg/genericclioptions"
 )
 
-var name string
+var opts = struct {
```
Comment (mainred) [inline cli/cmd/capture/capture.go:12]: Maybe we can borrow what kubectl cli has been achieved here? Like https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/create/create_cronjob.go

Comment (mainred) [reply cli/cmd/capture/capture.go:12]: ^^ it's for this change, we can improve later.
Thanks for fixing missing namespace flag.

Comment (rbtr) [reply cli/cmd/capture/capture.go:12]: That's the direction I am moving with this change, but it is just the first small step

File: cli/cmd/capture/create.go (hunk 1 above)
Comment (rbtr) [reply cli/cmd/capture/create.go:123]: Might be nice if we didn't have a global logger

Comment (timraymond) [reply cli/cmd/capture/create.go:123]: Filed #585

File: cli/cmd/capture/capture.go [hunk 3]
```diff
@@ -18,8 +21,8 @@ var capture = &cobra.Command{
 
 func init() {
 	cmd.Retina.AddCommand(capture)
-	configFlags = genericclioptions.NewConfigFlags(true)
-	configFlags.AddFlags(capture.PersistentFlags())
-	capture.PersistentFlags().StringVar(&name, "name", "", "The name of the Retina Capture")
+	opts.ConfigFlags = *genericclioptions.NewConfigFlags(true)
+	opts.AddFlags(capture.PersistentFlags())
+	capture.PersistentFlags().StringVar(opts.Name, "name", "", "The name of the Retina Capture")
```
Comment (timraymond) [inline cli/cmd/capture/capture.go:26]: I know it's a small thing here, but this might be better as a method of `opts`. You can inject whatever the value of `capture.PersistentFlags()` is and let opts add Flags to it. It'd make it a little more modular by letting the opts say "I know what my flags should be".

Not a blocker, but just an idea.

File: cli/cmd/capture/capture.go [hunk 4]
```diff
@@ -20,7 +23,8 @@ var capture = &cobra.Command{
 
 func init() {
 	cmd.Retina.AddCommand(capture)
-	configFlags = genericclioptions.NewConfigFlags(true)
-	configFlags.AddFlags(capture.PersistentFlags())
-	capture.PersistentFlags().StringVar(&name, "name", defaultName, "The name of the Retina Capture")
+	opts.ConfigFlags = *genericclioptions.NewConfigFlags(true)
+	opts.AddFlags(capture.PersistentFlags())
+	capture.PersistentFlags().StringVar(opts.Name, "name", defaultName, "The name of the Retina Capture")
+	_ = capture.MarkPersistentFlagRequired("name")
```
Comment (kamilprz) [inline cli/cmd/capture/capture.go:29]: Do we need to mark `name` as a required flag? I previously got rid of this considering we have a default value and the capture file names are unique because of the timestamp.

Comment (rbtr) [reply cli/cmd/capture/capture.go]: It snuck back in when I rebase/resolved conflicts. Removed

**Review by kamilprz — APPROVED** [review]

**Comment by rbtr** [comment]
not sure why my key is unverified, I'm signing in a codespace 😠
