### PR TITLE
fix(basic-metrics): Use fexit instead of kprobes for DropReason

### LINKED ISSUE #1451: Some drop reasons kernel return codes are ignored
`nf_hook_slow_ret` ignores the return code it gets from the kretprobe and always passes 0 along with its drop reason. This accidentally reduces the cadrinality of this metric, but also strips away potentially useful diagnostic info.
https://github.com/microsoft/retina/blob/main/pkg/plugin/dropreason/_cprog/drop_reason.c#L288
Same for `nf_nat_inet_fn_ret`
https://github.com/microsoft/retina/blob/main/pkg/plugin/dropreason/_cprog/drop_reason.c#L413

### LINKED ISSUE #1466: Some kernel return codes are always corrupted for DropReason
A few instances of passing a negative return code to an unsigned map key. THis always overflows, and the resulting metric value is partially meaningless.
Eg.: https://github.com/microsoft/retina/blob/main/pkg/plugin/dropreason/_cprog/drop_reason.c#L310

Related to #1451

### LINKED ISSUE #1469: DropReason should use atomics for drop count
__sync_fetch_and_add(&entry->count, 1);

### PR DESCRIPTION
**Pull request by rectified95**
### Description
`fexit` programs capture both the function arguments and the return value. By using them we don't need the pairs of kprobe-kretprobe programs to correlate program invocations for packets.

This reduces the number of syscalls by half, while this program type is also more efficient than kprobe, as measured by this benchmark: https://github.com/cloudflare/ebpf_exporter/tree/master/benchmark
I've reproduced it and have seen more moderate but noticeable differences.

The largest perf gain comes from slashing the number of eBPF program invocations.
This PR covers the "basic metrics" mode, and a follow-up is ready for the advanced scenario, removing kprobes altogether.

We use the new program type for kernel versions >= 5.5 (AMD64), 6.0 (ARM64) the existing kprobes for older kernels.
On Azure Linux (Mariner) we skip attaching certain eBPF programs; this distro currently doesn't contain BTF info for kernel modules, and some of the functions we attach to are outside of the core kernel.

#### 99% CPU 50 streams, MTU 100 B, cross-node pods
- w/o Retina: **8.4**
- w/ this PR: **8.17**
- w/o this PR: **6.2**

#### Single TCP stream, same node pods
- w/o Retina: **21.2**
- w/ this PR: **20.5**
- w/ this PR, all dropped: 19.7 (unconditionally execute entire programs, forcing map lookups)
- w/o this PR: **17.2**

#### 50 streams, default MTU, same node
- w/o Retina: **420**
- w/ this PR: **400**
- w/o this PR: **40**

#### 50 streams, default MTU, cross-node
30Gbps achieved for all.

### Other changes: 
- fix overflow when storing kernel nagative return codes in an unsigned type
- fix some kernel return codes being ignored and not recorded
- fix drop packet counter not using atomic increment
- fix up error formatting using `zap`

Fixes #1469 
Fixes #1466
Fixes #1451
Related https://github.com/microsoft/retina/issues/715

### CODE REVIEW

File: pkg/plugin/dropreason/_cprog/drop_reason.c [hunk 1]
```diff
@@ -28,7 +28,8 @@ char __license[] SEC("license") = "Dual MIT/GPL";
 struct metrics_map_key
 {
     __u16 drop_type;
-    __u32 return_val;
+    __u8 padding[2];
```
Comment (rectified95) [inline pkg/plugin/dropreason/_cprog/drop_reason.c:31]: Need aligned access, clang didn't add padding

File: pkg/plugin/dropreason/_cprog/drop_reason.c [hunk 2]
```diff
@@ -108,11 +110,12 @@ struct
             member_address(source_struct, source_member));     \
     } while (0)
 
+// Updates dropped packets stats - ONLY use in Retina advanced.
 void update_metrics_map(void *ctx, drop_reason_t drop_type, int ret_val, struct packet *p)
 {
     struct metrics_map_value *entry, new_entry = {};
     struct metrics_map_key key;
-    __builtin_memset(&key, 0, sizeof(p));
+    __builtin_memset(&key, 0, sizeof(key));
```
Comment (rectified95) [inline pkg/plugin/dropreason/_cprog/drop_reason.c:118]: this was wrong

File: pkg/plugin/dropreason/_cprog/drop_reason.c [hunk 3]
```diff
@@ -285,15 +303,27 @@ int BPF_KRETPROBE(nf_hook_slow_ret, int retVal)
 
     bpf_map_delete_elem(&retina_dropreason_drop_pids, &pid);
 
-    update_metrics_map(ctx, IPTABLE_RULE_DROP, 0, p);
+    update_metrics_map(ctx, IPTABLE_RULE_DROP, retVal, p);
```
Comment (rectified95) [inline pkg/plugin/dropreason/_cprog/drop_reason.c:306]: pass actual return val isntead of zero

**Review by nddq — APPROVED** [review]
some minor comments but otherwise lgtm

File: pkg/plugin/dropreason/dropreason_linux.go [hunk 4]
```diff
@@ -444,13 +398,147 @@ func (dr *dropReason) processMapValue(dataKey dropMetricKey, dataValue dropMetri
...
 	dr.l.Debug("DATA From the DropReason Map", zap.String("Droptype", dataKey.getType()),
-		zap.Uint32("Return Val", dataKey.ReturnVal),
+		zap.Int32("Return Val", dataKey.ReturnVal),
 		zap.Int("DropCount", int(pktCount)),
 		zap.Int("DropBytes", int(pktBytes)))
 
 	dr.dropMetricAdd(dataKey.getType(), dataKey.getDirection(), pktCount, pktBytes)
 }
 
+func (dr *dropReason) attachKprobes(objs *kprobeObjects) error {
```
[the remark this answers is not in the document]
Comment (rectified95) [reply pkg/plugin/dropreason/dropreason_linux.go:408]: i can do that in the follow-up PR for advanced metrics

File: pkg/plugin/dropreason/dropreason_linux.go [hunk 5]
```diff
@@ -444,13 +398,147 @@ func (dr *dropReason) processMapValue(dataKey dropMetricKey, dataValue dropMetri
...
+	var err error
+
+	dr.KNfHook, err = link.Kprobe(nfHookSlowFn, objs.NfHookSlow, nil)
+	if err != nil {
+		dr.l.Error("opening kprobe", zap.Error(err))
+		return fmt.Errorf("Failed to attach program: %w", err) //nolint:goerr113 //wrapping error from external module
```
[the remark this answers is not in the document]
Comment (rectified95) [reply pkg/plugin/dropreason/dropreason_linux.go:414]: doesn't fmt.Errorf wrap as well?

[the remark this answers is not in the document]
Comment (nddq) [reply pkg/plugin/dropreason/dropreason_linux.go:414]: does it? if we remove `//nolint:goerr113`, does the linter has an issue with it?

[the remark this answers is not in the document]
Comment (rectified95) [reply pkg/plugin/dropreason/dropreason_linux.go:414]: It does, see here: https://docs.datadoghq.com/security/code_security/static_analysis/static_analysis_rules/go-best-practices/errors-new-errorf/

I added this linter ignore because somehow it doesn't correctly recognize the wrapping

File: deploy/standard/manifests/controller/helm/retina/values.yaml [hunk 6]
```diff
@@ -98,6 +98,7 @@ volumeMounts:
   cgroup: /sys/fs/cgroup
   tmp: /tmp
   config: /retina/config
+  host-os-release: /etc/os-release
```
Comment (rectified95) [inline deploy/standard/manifests/controller/helm/retina/values.yaml:101]: This volumeMount is needed to determine if the host is Mariner, so we can decide which ebpf programs to attach. 
Retina's base image is Mariner, so the file scan of /etc/os-release would always return true otherwise.

File: pkg/plugin/common/common_linux.go [hunk 7]
```diff
@@ -89,3 +94,47 @@ func NewPerfReader(l *log.ZapLogger, m *ebpf.Map, max, min int) (*perf.Reader, e
 	}
 	return nil, errors.New("failed to create perf reader")
 }
+
+// Function to only extract the X.Y version components, used as fallback for version.GetKernelVersion()
+// Needed for images which don't follow standard Linux version format, e.g.: 5.15.153.1-microsoft-standard-WSL2
+func GetKernelVersionMajMin() (semver.Version, error) {
+	var unameBuf unix.Utsname
+	if err := unix.Uname(&unameBuf); err != nil {
+		return semver.Version{}, err //nolint:wrapcheck // no additional context needed
```
Comment (MikeZappa87) [inline pkg/plugin/common/common_linux.go:103]: return nil, err?

File: test/plugin/dropreason/main_linux.go [hunk 8]
```diff
@@ -67,31 +67,31 @@ func main() {
 
 	err = tt.Stop()
 	if err != nil {
-		l.Error("Stop failed:%v", zap.Error(err))
+		l.Error("Stop failed:", zap.Error(err))
```
Comment (MikeZappa87) [inline test/plugin/dropreason/main_linux.go:70]: nit: these log statement changes should have been in a different PR.

File: deploy/standard/manifests/controller/helm/retina/values.yaml (hunk 6 above)
Comment (MikeZappa87) [inline deploy/standard/manifests/controller/helm/retina/values.yaml:101]: I have come across distros where this file is missing since this is open source we should be aware of this. I don't believe Linux states this MUST be present.

File: test/plugin/dropreason/main_linux.go (hunk 8 above)
Comment (rectified95) [reply test/plugin/dropreason/main_linux.go:70]: Not required, just saw garbled logs so fixed the,

File: deploy/standard/manifests/controller/helm/retina/values.yaml (hunk 6 above)
Comment (rectified95) [reply deploy/standard/manifests/controller/helm/retina/values.yaml:101]: Right, it's a standard, for not required. Hb this: I remove `Type: File`, and we'll avoid pod start failures if file is missing, k8s will mount and empty dir, which the code handles.

Comment (rectified95) [reply deploy/standard/manifests/controller/helm/retina/values.yaml:101]: @MikeZappa87 Changed this to `FileOrCreate` to avoid pods stuck in Init. Mariner will always have this file non-empty, so this fallback will correctly apply for non-Mariner distros. 
I tested this logic manually.

**Review by matmerr — APPROVED** [review]
